server:
  port: 9091

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.bistu.why.model
  global-config:
    db-config:
      id-type: auto
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.58.190:3306/second_hand?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: 192.168.58.190
    port: 6379
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #rabbimq
  rabbitmq:
    host: 192.168.58.190
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    #发送者到交换机 确认模式
    #交换机到队列的回调
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          #重试3次
          max-attempts: 3
    publisher-confirm-type: correlated
  thymeleaf:
    cache: false
    encoding: UTF-8
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: product_
      cache-null-values: true
      time-to-live: 300s
file:
  upload: \\src\\main\\resources\\upload\\file

ali:
  appSecret: 15J9qFRyPxAmKgDvbnMH3lDOhE3c71DV
  appKey: 204098293
  appCode: 31eb5e7be01f4209ba2dd486bf494887
thread:
  coreSize: 20
  maxSize: 200
  keepAliveTime: 10

