spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.58.190:3306/second_hand?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  redis:
    host: 192.168.58.190
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: second-hand-mall-admin
  web:
    resources:
      static-locations: classpath:/templates/
  thymeleaf:
    cache: false
  #rabbimq
  rabbitmq:
    host: 192.168.58.190
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    #确认模式
    publisher-confirm-type: correlated
    #发送者的回调 交换机到队列的回调
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          #重试3次
          max-attempts: 3

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bistu.why.admin.entity
server:
  port: 9090

