INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (27, 17, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 11 最新款 pro max', 'iphone 11 最新款 pro max', 5300.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (28, 17, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 12 最新款 pro max max', 'iphone 11 最新款 pro max', 5800.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (29, 17, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 12 最新款 pro max max', 'iphone 11 最新款 pro max', 5800.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (30, 18, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 11 最新款 pro max', 'iphone 11 最新款 pro max', 5300.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (31, 18, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 12 最新款 pro max max', 'iphone 11 最新款 pro max', 5800.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (32, 18, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 12 最新款 pro max max', 'iphone 11 最新款 pro max', 5800.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (33, 19, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 11 最新款 pro max', 'iphone 11 最新款 pro max', 5300.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (34, 19, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 12 最新款 pro max max', 'iphone 11 最新款 pro max', 5800.0000, 10);
INSERT INTO `second_hand_sku_info`(`sku_id`, `spu_id`, `sku_name`, `catalog_id`, `brand_id`, `sku_default_img`, `sku_title`, `sku_subtitle`, `price`, `sale_count`) VALUES (35, 19, 'Apple IPhone13', 225, 1, 'sku_img1', 'iphone 12 最新款 pro max max', 'iphone 11 最新款 pro max', 5800.0000, 10);
